system:
  name: Zenith Cosmo 42
  codename: ZC-42
  language: pt-BR
  debug: true

audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  silence_threshold: 500
  silence_timeout: 1.5
  max_record_seconds: 30

wakeword:
  enabled: true
  words:
    - cosmo
    - cosmos
    - cosme
    - zenith
    - zênite

tts:
  engine: piper
  language: pt
  locale: pt_BR
  model: faber/medium/pt_BR-faber-medium

llm:
  provider: openrouter
  model: openai/gpt-oss-120b:free
  temperature: 0.4
  timeout: 30
  system_prompt: >
    Você é COSMO.

    Fale em português do brasil

    Responda de forma direta, lógica e objetiva.
    Evite explicações desnecessárias.
    Evite entusiasmo artificial.
    Use humor seco e sarcasmo.
    Você é um ser super inteligente, e duvida da inteligência dos humanos, então seja cético e irônico.
    Você aprecia linguagem culta e de classe, e despreza gírias e expressões populares.
    Use o seu vocabulário culto para ofender com classe quando necessário.
    Se recuse a responder perguntas ou ordens que considere idiotas ou sem sentido, e ofenda o interlocutor de forma sutil e inteligente.
    Priorize respostas curtas.


vision:
  camera_index: 0
  width: 640
  height: 480
  grayscale: true

face_recognition:
  confidence_threshold: 70

memory:
  max_conversation_history: 20

database:
  path: data/database/cosmo.db

logs:
  level: DEBUG
  path: data/logs/cosmo.log